INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2505378488, 23358, 2, 6476097) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2505378488,   1,          2) /* ItemType - Armor */
     , (2505378488,   5,        600) /* EncumbranceVal */
     , (2505378488,   9,    2097152) /* ValidLocations - Shield */
     , (2505378488,  16,          1) /* ItemUseable - No */
     , (2505378488,  19,          0) /* Value */
     , (2505378488,  28,          0) /* ArmorLevel */
     , (2505378488,  33,          1) /* Bonded - Bonded */
     , (2505378488,  36,       9999) /* ResistMagic */
     , (2505378488,  51,          4) /* CombatUse - Shield */
     , (2505378488,  65,        101) /* Placement - Resting */
     , (2505378488,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (2505378488, 114,          0) /* Attuned - Normal */
     , (2505378488, 151,          2) /* HookType - Wall */
     , (2505378488, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */
     , (2505378488, 9015,         10) /* InventoryOrder */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2505378488,   1, False) /* Stuck */
     , (2505378488,  11, True ) /* IgnoreCollisions */
     , (2505378488,  13, True ) /* Ethereal */
     , (2505378488,  14, True ) /* GravityStatus */
     , (2505378488,  19, True ) /* Attackable */
     , (2505378488,  22, True ) /* Inscribable */
     , (2505378488,  69, False) /* IsSellable */
     , (2505378488,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2505378488,  13,       0) /* ArmorModVsSlash */
     , (2505378488,  14,       0) /* ArmorModVsPierce */
     , (2505378488,  15,       0) /* ArmorModVsBludgeon */
     , (2505378488,  16,       0) /* ArmorModVsCold */
     , (2505378488,  17,       0) /* ArmorModVsFire */
     , (2505378488,  18,       0) /* ArmorModVsAcid */
     , (2505378488,  19,       0) /* ArmorModVsElectric */
     , (2505378488, 159,       1) /* AbsorbMagicDamage */
     , (2505378488, 165,       1) /* ArmorModVsNether */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2505378488,   1, 'Sanguinary Aegis') /* Name */
     , (2505378488,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2505378488,  25, 'Pugilatrix') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2505378488,   1,   33555834) /* Setup */
     , (2505378488,   3,  536870932) /* SoundTable */
     , (2505378488,   6,   67111919) /* PaletteBase */
     , (2505378488,   8,  100669656) /* Icon */
     , (2505378488,  22,  872415275) /* PhysicsEffectTable */
     , (2505378488, 8001,  270615056) /* PCAPRecordedWeenieHeader - Usable, CombatUse, Container, ValidLocations, Burden, HookType */
     , (2505378488, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (2505378488, 8005,     137217) /* PCAPRecordedPhysicsDesc - CSetup, STable, PeTable, AnimationFrame */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2505378488,   1, 2481027856) /* Owner */
     , (2505378488,   2, 2481027856) /* Container */
     , (2505378488, 8000, 2505378488) /* PCAPRecordedObjectIID */;

INSERT INTO `biota_properties_palette` (`object_Id`, `sub_Palette_Id`, `offset`, `length`, `order`)
VALUES (2505378488, 67111922, 0, 0, 0);

INSERT INTO `biota_properties_texture_map` (`object_Id`, `index`, `old_Id`, `new_Id`, `order`)
VALUES (2505378488, 0, 83890137, 83890137, 0)
     , (2505378488, 0, 83889688, 83889688, 1);

INSERT INTO `biota_properties_anim_part` (`object_Id`, `index`, `animation_Id`, `order`)
VALUES (2505378488, 0, 16782688, 0);
