INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2149747651, 23359, 2, 2150720) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2149747651,   1,          2) /* ItemType - Armor */
     , (2149747651,   5,        600) /* EncumbranceVal */
     , (2149747651,   9,    2097152) /* ValidLocations - Shield */
     , (2149747651,  19,         -1) /* Value */
     , (2149747651,  28,          0) /* ArmorLevel */
     , (2149747651,  33,          1) /* Bonded - Bonded */
     , (2149747651,  36,       9999) /* ResistMagic */
     , (2149747651,  51,          4) /* CombatUse - Shield */
     , (2149747651, 107,          0) /* ItemCurMana */
     , (2149747651, 108,          0) /* ItemMaxMana */
     , (2149747651, 114,          0) /* Attuned - Normal */
     , (2149747651, 151,          2) /* HookType - Wall */
     , (2149747651, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2149747651,  69, False) /* IsSellable */
     , (2149747651,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2149747651,  13,       0) /* ArmorModVsSlash */
     , (2149747651,  14,       0) /* ArmorModVsPierce */
     , (2149747651,  15,       0) /* ArmorModVsBludgeon */
     , (2149747651,  16,       0) /* ArmorModVsCold */
     , (2149747651,  17,       0) /* ArmorModVsFire */
     , (2149747651,  18,       0) /* ArmorModVsAcid */
     , (2149747651,  19,       0) /* ArmorModVsElectric */
     , (2149747651, 159,       1) /* AbsorbMagicDamage */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2149747651,   1, 'Sanguinary Aegis') /* Name */
     , (2149747651,   7, 'May this shield help Immortalbob better protect Dereth from its foes and aid him in winning future contests.  "So close, yet so far away"') /* Inscription */
     , (2149747651,   8, '+Leo Barracuda') /* ScribeName */
     , (2149747651,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2149747651,  25, 'Immortalbob') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2149747651,   1,   33555835) /* Setup */
     , (2149747651,   8,       6364) /* Icon */
     , (2149747651, 8003,         16) /* PCAPRecordedObjectDesc - Attackable */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2149747651,   2, 1343229927) /* Container */
     , (2149747651,   3,          0) /* Wielder */;
