INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2151959813, 23360, 2, 6476097) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2151959813,   1,          2) /* ItemType - Armor */
     , (2151959813,   5,        600) /* EncumbranceVal */
     , (2151959813,   9,    2097152) /* ValidLocations - Shield */
     , (2151959813,  16,          1) /* ItemUseable - No */
     , (2151959813,  19,          0) /* Value */
     , (2151959813,  28,          0) /* ArmorLevel */
     , (2151959813,  33,          1) /* Bonded - Bonded */
     , (2151959813,  36,       9999) /* ResistMagic */
     , (2151959813,  51,          4) /* CombatUse - Shield */
     , (2151959813,  65,        101) /* Placement - Resting */
     , (2151959813,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (2151959813, 114,          0) /* Attuned - Normal */
     , (2151959813, 151,          2) /* HookType - Wall */
     , (2151959813, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */
     , (2151959813, 9015,          5) /* InventoryOrder */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2151959813,   1, False) /* Stuck */
     , (2151959813,  11, True ) /* IgnoreCollisions */
     , (2151959813,  13, True ) /* Ethereal */
     , (2151959813,  14, True ) /* GravityStatus */
     , (2151959813,  19, True ) /* Attackable */
     , (2151959813,  22, True ) /* Inscribable */
     , (2151959813,  69, False) /* IsSellable */
     , (2151959813,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2151959813,  13,       0) /* ArmorModVsSlash */
     , (2151959813,  14,       0) /* ArmorModVsPierce */
     , (2151959813,  15,       0) /* ArmorModVsBludgeon */
     , (2151959813,  16,       0) /* ArmorModVsCold */
     , (2151959813,  17,       0) /* ArmorModVsFire */
     , (2151959813,  18,       0) /* ArmorModVsAcid */
     , (2151959813,  19,       0) /* ArmorModVsElectric */
     , (2151959813, 159,       1) /* AbsorbMagicDamage */
     , (2151959813, 165,       1) /* ArmorModVsNether */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2151959813,   1, 'Sanguinary Aegis') /* Name */
     , (2151959813,   7, 'Former Advocate Ripley') /* Inscription */
     , (2151959813,   8, 'Ripley') /* ScribeName */
     , (2151959813,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2151959813,  25, 'Ripley') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2151959813,   1,   33555836) /* Setup */
     , (2151959813,   3,  536870932) /* SoundTable */
     , (2151959813,   6,   67111919) /* PaletteBase */
     , (2151959813,   8,  100669654) /* Icon */
     , (2151959813,  22,  872415275) /* PhysicsEffectTable */
     , (2151959813, 8001,  270615056) /* PCAPRecordedWeenieHeader - Usable, CombatUse, Container, ValidLocations, Burden, HookType */
     , (2151959813, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (2151959813, 8005,     137217) /* PCAPRecordedPhysicsDesc - CSetup, STable, PeTable, AnimationFrame */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2151959813,   1, 2186220426) /* Owner */
     , (2151959813,   2, 2186220426) /* Container */
     , (2151959813, 8000, 2151959813) /* PCAPRecordedObjectIID */;

INSERT INTO `biota_properties_palette` (`object_Id`, `sub_Palette_Id`, `offset`, `length`)
VALUES (2151959813, 67111920, 0, 0);

INSERT INTO `biota_properties_texture_map` (`object_Id`, `index`, `old_Id`, `new_Id`, `order`)
VALUES (2151959813, 0, 83890137, 83890137, 0)
     , (2151959813, 0, 83889688, 83889688, 1);

INSERT INTO `biota_properties_anim_part` (`object_Id`, `index`, `animation_Id`, `order`)
VALUES (2151959813, 0, 16782688, 0);
