INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2186220611, 23359, 2, 6476097) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2186220611,   1,          2) /* ItemType - Armor */
     , (2186220611,   5,        600) /* EncumbranceVal */
     , (2186220611,   9,    2097152) /* ValidLocations - Shield */
     , (2186220611,  16,          1) /* ItemUseable - No */
     , (2186220611,  19,          0) /* Value */
     , (2186220611,  28,          0) /* ArmorLevel */
     , (2186220611,  33,          1) /* Bonded - Bonded */
     , (2186220611,  36,       9999) /* ResistMagic */
     , (2186220611,  51,          4) /* CombatUse - Shield */
     , (2186220611,  65,        101) /* Placement - Resting */
     , (2186220611,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (2186220611, 114,          0) /* Attuned - Normal */
     , (2186220611, 151,          2) /* HookType - Wall */
     , (2186220611, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */
     , (2186220611, 9015,          0) /* InventoryOrder */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2186220611,   1, False) /* Stuck */
     , (2186220611,  11, True ) /* IgnoreCollisions */
     , (2186220611,  13, True ) /* Ethereal */
     , (2186220611,  14, True ) /* GravityStatus */
     , (2186220611,  19, True ) /* Attackable */
     , (2186220611,  22, True ) /* Inscribable */
     , (2186220611,  69, False) /* IsSellable */
     , (2186220611,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2186220611,  13,       0) /* ArmorModVsSlash */
     , (2186220611,  14,       0) /* ArmorModVsPierce */
     , (2186220611,  15,       0) /* ArmorModVsBludgeon */
     , (2186220611,  16,       0) /* ArmorModVsCold */
     , (2186220611,  17,       0) /* ArmorModVsFire */
     , (2186220611,  18,       0) /* ArmorModVsAcid */
     , (2186220611,  19,       0) /* ArmorModVsElectric */
     , (2186220611, 159,       1) /* AbsorbMagicDamage */
     , (2186220611, 165,       1) /* ArmorModVsNether */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2186220611,   1, 'Sanguinary Aegis') /* Name */
     , (2186220611,   7, 'Former Advocate Ripley, Still helping players after the disbandment! ;)') /* Inscription */
     , (2186220611,   8, 'Ripley') /* ScribeName */
     , (2186220611,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2186220611,  25, 'Ripley') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2186220611,   1,   33555835) /* Setup */
     , (2186220611,   3,  536870932) /* SoundTable */
     , (2186220611,   6,   67111919) /* PaletteBase */
     , (2186220611,   8,  100669660) /* Icon */
     , (2186220611,  22,  872415275) /* PhysicsEffectTable */
     , (2186220611, 8001,  270615056) /* PCAPRecordedWeenieHeader - Usable, CombatUse, Container, ValidLocations, Burden, HookType */
     , (2186220611, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (2186220611, 8005,     137217) /* PCAPRecordedPhysicsDesc - CSetup, STable, PeTable, AnimationFrame */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2186220611,   1, 2186220449) /* Owner */
     , (2186220611,   2, 2186220449) /* Container */
     , (2186220611, 8000, 2186220611) /* PCAPRecordedObjectIID */;

INSERT INTO `biota_properties_palette` (`object_Id`, `sub_Palette_Id`, `offset`, `length`)
VALUES (2186220611, 67111924, 0, 0);

INSERT INTO `biota_properties_texture_map` (`object_Id`, `index`, `old_Id`, `new_Id`, `order`)
VALUES (2186220611, 0, 83890137, 83890137, 0)
     , (2186220611, 0, 83889688, 83889688, 1);

INSERT INTO `biota_properties_anim_part` (`object_Id`, `index`, `animation_Id`, `order`)
VALUES (2186220611, 0, 16782688, 0);
