INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2147858972, 23359, 2, 2150720) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2147858972,   1,          2) /* ItemType - Armor */
     , (2147858972,   5,        600) /* EncumbranceVal */
     , (2147858972,   9,    2097152) /* ValidLocations - Shield */
     , (2147858972,  19,          0) /* Value */
     , (2147858972,  28,          0) /* ArmorLevel */
     , (2147858972,  33,          1) /* Bonded - Bonded */
     , (2147858972,  36,       9999) /* ResistMagic */
     , (2147858972,  51,          4) /* CombatUse - Shield */
     , (2147858972, 114,          0) /* Attuned - Normal */
     , (2147858972, 151,          2) /* HookType - Wall */
     , (2147858972, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2147858972,  69, False) /* IsSellable */
     , (2147858972,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2147858972,  13,       0) /* ArmorModVsSlash */
     , (2147858972,  14,       0) /* ArmorModVsPierce */
     , (2147858972,  15,       0) /* ArmorModVsBludgeon */
     , (2147858972,  16,       0) /* ArmorModVsCold */
     , (2147858972,  17,       0) /* ArmorModVsFire */
     , (2147858972,  18,       0) /* ArmorModVsAcid */
     , (2147858972,  19,       0) /* ArmorModVsElectric */
     , (2147858972, 159,       1) /* AbsorbMagicDamage */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2147858972,   1, 'Sanguinary Aegis') /* Name */
     , (2147858972,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2147858972,  25, 'Dm Gatherer') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2147858972,   1,   33555835) /* Setup */
     , (2147858972,   8,       6364) /* Icon */
     , (2147858972, 8003,         16) /* PCAPRecordedObjectDesc - Attackable */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2147858972,   2, 2147859081) /* Container */;
