INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2264749490, 23360, 2, 2150720) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2264749490,   1,          2) /* ItemType - Armor */
     , (2264749490,   5,        600) /* EncumbranceVal */
     , (2264749490,   9,    2097152) /* ValidLocations - Shield */
     , (2264749490,  19,         -1) /* Value */
     , (2264749490,  28,          0) /* ArmorLevel */
     , (2264749490,  33,          1) /* Bonded - Bonded */
     , (2264749490,  36,       9999) /* ResistMagic */
     , (2264749490,  51,          4) /* CombatUse - Shield */
     , (2264749490, 114,          0) /* Attuned - Normal */
     , (2264749490, 151,          2) /* HookType - Wall */
     , (2264749490, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2264749490,  69, False) /* IsSellable */
     , (2264749490,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2264749490,  13,       0) /* ArmorModVsSlash */
     , (2264749490,  14,       0) /* ArmorModVsPierce */
     , (2264749490,  15,       0) /* ArmorModVsBludgeon */
     , (2264749490,  16,       0) /* ArmorModVsCold */
     , (2264749490,  17,       0) /* ArmorModVsFire */
     , (2264749490,  18,       0) /* ArmorModVsAcid */
     , (2264749490,  19,       0) /* ArmorModVsElectric */
     , (2264749490, 159,       1) /* AbsorbMagicDamage */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2264749490,   1, 'Sanguinary Aegis') /* Name */
     , (2264749490,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2264749490,  25, 'Confused') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2264749490,   1,   33555836) /* Setup */
     , (2264749490,   8,       6358) /* Icon */
     , (2264749490, 8003,         16) /* PCAPRecordedObjectDesc - Attackable */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2264749490,   2, 2266482268) /* Container */;
