INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (3674521601, 31395, 2, 7393601) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (3674521601,   1,          2) /* ItemType - Armor */
     , (3674521601,   5,        600) /* EncumbranceVal */
     , (3674521601,   9,    2097152) /* ValidLocations - Shield */
     , (3674521601,  16,          1) /* ItemUseable - No */
     , (3674521601,  18,         32) /* UiEffects - Fire */
     , (3674521601,  19,          0) /* Value */
     , (3674521601,  28,          0) /* ArmorLevel */
     , (3674521601,  33,          1) /* Bonded - Bonded */
     , (3674521601,  36,       9999) /* ResistMagic */
     , (3674521601,  51,          4) /* CombatUse - Shield */
     , (3674521601,  65,        101) /* Placement - Resting */
     , (3674521601,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (3674521601, 106,        350) /* ItemSpellcraft */
     , (3674521601, 107,       2634) /* ItemCurMana */
     , (3674521601, 108,       3000) /* ItemMaxMana */
     , (3674521601, 114,          0) /* Attuned - Normal */
     , (3674521601, 115,        400) /* ItemSkillLevelLimit */
     , (3674521601, 151,          2) /* HookType - Wall */
     , (3674521601, 158,          7) /* WieldRequirements - Level */
     , (3674521601, 159,          1) /* WieldSkillType - Axe */
     , (3674521601, 160,        100) /* WieldDifficulty */
     , (3674521601, 176,          6) /* AppraisalItemSkill */
     , (3674521601, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */
     , (3674521601, 9015,         43) /* InventoryOrder */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (3674521601,   1, False) /* Stuck */
     , (3674521601,  11, True ) /* IgnoreCollisions */
     , (3674521601,  13, True ) /* Ethereal */
     , (3674521601,  14, True ) /* GravityStatus */
     , (3674521601,  19, True ) /* Attackable */
     , (3674521601,  22, True ) /* Inscribable */
     , (3674521601,  69, False) /* IsSellable */
     , (3674521601,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (3674521601,   5,  -0.025) /* ManaRate */
     , (3674521601,  13,       0) /* ArmorModVsSlash */
     , (3674521601,  14,       0) /* ArmorModVsPierce */
     , (3674521601,  15,       0) /* ArmorModVsBludgeon */
     , (3674521601,  16,       0) /* ArmorModVsCold */
     , (3674521601,  17,       0) /* ArmorModVsFire */
     , (3674521601,  18,       0) /* ArmorModVsAcid */
     , (3674521601,  19,       0) /* ArmorModVsElectric */
     , (3674521601, 159,       1) /* AbsorbMagicDamage */
     , (3674521601, 165,       1) /* ArmorModVsNether */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (3674521601,   1, 'Raven Aegis') /* Name */
     , (3674521601,  16, 'A magically imbued Aegis crafted by the Order of the Raven Hand.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (3674521601,  25, 'Callaway') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (3674521601,   1,   33559617) /* Setup */
     , (3674521601,   3,  536870932) /* SoundTable */
     , (3674521601,   8,  100687958) /* Icon */
     , (3674521601,  22,  872415275) /* PhysicsEffectTable */
     , (3674521601, 8001,  270615184) /* PCAPRecordedWeenieHeader - Usable, UiEffects, CombatUse, Container, ValidLocations, Burden, HookType */
     , (3674521601, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (3674521601, 8005,     137217) /* PCAPRecordedPhysicsDesc - CSetup, STable, PeTable, AnimationFrame */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (3674521601,   1, 1343301116) /* Owner */
     , (3674521601,   2, 1343301116) /* Container */
     , (3674521601, 8000, 3674521601) /* PCAPRecordedObjectIID */;

INSERT INTO `biota_properties_spell_book` (`object_Id`, `spell`, `probability`)
VALUES (3674521601,   249,      2) 
     , (3674521601,  3819,      2) 
     , (3674521601,  3820,      2) ;

INSERT INTO `biota_properties_texture_map` (`object_Id`, `index`, `old_Id`, `new_Id`, `order`)
VALUES (3674521601, 0, 83897328, 83897328, 0);

INSERT INTO `biota_properties_anim_part` (`object_Id`, `index`, `animation_Id`, `order`)
VALUES (3674521601, 0, 16792592, 0);
