INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2154446386, 23356, 2, 2150720) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2154446386,   1,          2) /* ItemType - Armor */
     , (2154446386,   5,        600) /* EncumbranceVal */
     , (2154446386,   9,    2097152) /* ValidLocations - Shield */
     , (2154446386,  19,         -1) /* Value */
     , (2154446386,  28,          0) /* ArmorLevel */
     , (2154446386,  33,          1) /* Bonded - Bonded */
     , (2154446386,  36,       9999) /* ResistMagic */
     , (2154446386,  51,          4) /* CombatUse - Shield */
     , (2154446386, 114,          0) /* Attuned - Normal */
     , (2154446386, 151,          2) /* HookType - Wall */
     , (2154446386, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2154446386,  69, False) /* IsSellable */
     , (2154446386,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2154446386,  13,       0) /* ArmorModVsSlash */
     , (2154446386,  14,       0) /* ArmorModVsPierce */
     , (2154446386,  15,       0) /* ArmorModVsBludgeon */
     , (2154446386,  16,       0) /* ArmorModVsCold */
     , (2154446386,  17,       0) /* ArmorModVsFire */
     , (2154446386,  18,       0) /* ArmorModVsAcid */
     , (2154446386,  19,       0) /* ArmorModVsElectric */
     , (2154446386, 159,       1) /* AbsorbMagicDamage */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2154446386,   1, 'Sanguinary Aegis') /* Name */
     , (2154446386,   7, 'Yo there') /* Inscription */
     , (2154446386,   8, 'Mackdaddy Jr') /* ScribeName */
     , (2154446386,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2154446386,  25, 'Mackdaddy Jr') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2154446386,   1,   33555831) /* Setup */
     , (2154446386,   8,       6357) /* Icon */
     , (2154446386, 8003,         16) /* PCAPRecordedObjectDesc - Attackable */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2154446386,   2, 1343006379) /* Container */;
