INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2943503599, 23358, 2, 6476097) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2943503599,   1,          2) /* ItemType - Armor */
     , (2943503599,   5,        600) /* EncumbranceVal */
     , (2943503599,   9,    2097152) /* ValidLocations - Shield */
     , (2943503599,  16,          1) /* ItemUseable - No */
     , (2943503599,  19,          0) /* Value */
     , (2943503599,  28,          0) /* ArmorLevel */
     , (2943503599,  33,          1) /* Bonded - Bonded */
     , (2943503599,  36,       9999) /* ResistMagic */
     , (2943503599,  51,          4) /* CombatUse - Shield */
     , (2943503599,  65,        101) /* Placement - Resting */
     , (2943503599,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (2943503599, 114,          0) /* Attuned - Normal */
     , (2943503599, 151,          2) /* HookType - Wall */
     , (2943503599, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */
     , (2943503599, 9015,          9) /* InventoryOrder */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2943503599,   1, False) /* Stuck */
     , (2943503599,  11, True ) /* IgnoreCollisions */
     , (2943503599,  13, True ) /* Ethereal */
     , (2943503599,  14, True ) /* GravityStatus */
     , (2943503599,  19, True ) /* Attackable */
     , (2943503599,  22, True ) /* Inscribable */
     , (2943503599,  69, False) /* IsSellable */
     , (2943503599,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2943503599,  13,       0) /* ArmorModVsSlash */
     , (2943503599,  14,       0) /* ArmorModVsPierce */
     , (2943503599,  15,       0) /* ArmorModVsBludgeon */
     , (2943503599,  16,       0) /* ArmorModVsCold */
     , (2943503599,  17,       0) /* ArmorModVsFire */
     , (2943503599,  18,       0) /* ArmorModVsAcid */
     , (2943503599,  19,       0) /* ArmorModVsElectric */
     , (2943503599, 159,       1) /* AbsorbMagicDamage */
     , (2943503599, 165,       1) /* ArmorModVsNether */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2943503599,   1, 'Sanguinary Aegis') /* Name */
     , (2943503599,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2943503599,  25, 'Minaris') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2943503599,   1,   33555834) /* Setup */
     , (2943503599,   3,  536870932) /* SoundTable */
     , (2943503599,   6,   67111919) /* PaletteBase */
     , (2943503599,   8,  100669656) /* Icon */
     , (2943503599,  22,  872415275) /* PhysicsEffectTable */
     , (2943503599, 8001,  270615056) /* PCAPRecordedWeenieHeader - Usable, CombatUse, Container, ValidLocations, Burden, HookType */
     , (2943503599, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (2943503599, 8005,     137217) /* PCAPRecordedPhysicsDesc - CSetup, STable, PeTable, AnimationFrame */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2943503599,   1, 1342479658) /* Owner */
     , (2943503599,   2, 1342479658) /* Container */
     , (2943503599, 8000, 2943503599) /* PCAPRecordedObjectIID */;

INSERT INTO `biota_properties_palette` (`object_Id`, `sub_Palette_Id`, `offset`, `length`)
VALUES (2943503599, 67111922, 0, 0);

INSERT INTO `biota_properties_texture_map` (`object_Id`, `index`, `old_Id`, `new_Id`, `order`)
VALUES (2943503599, 0, 83890137, 83890137, 0)
     , (2943503599, 0, 83889688, 83889688, 1);

INSERT INTO `biota_properties_anim_part` (`object_Id`, `index`, `animation_Id`, `order`)
VALUES (2943503599, 0, 16782688, 0);
