INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2155768933, 23358, 2, 2150720) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2155768933,   1,          2) /* ItemType - Armor */
     , (2155768933,   5,        600) /* EncumbranceVal */
     , (2155768933,   9,    2097152) /* ValidLocations - Shield */
     , (2155768933,  19,         -1) /* Value */
     , (2155768933,  28,          0) /* ArmorLevel */
     , (2155768933,  33,          1) /* Bonded - Bonded */
     , (2155768933,  36,       9999) /* ResistMagic */
     , (2155768933,  51,          4) /* CombatUse - Shield */
     , (2155768933, 114,          0) /* Attuned - Normal */
     , (2155768933, 151,          2) /* HookType - Wall */
     , (2155768933, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2155768933,  69, False) /* IsSellable */
     , (2155768933,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2155768933,  13,       0) /* ArmorModVsSlash */
     , (2155768933,  14,       0) /* ArmorModVsPierce */
     , (2155768933,  15,       0) /* ArmorModVsBludgeon */
     , (2155768933,  16,       0) /* ArmorModVsCold */
     , (2155768933,  17,       0) /* ArmorModVsFire */
     , (2155768933,  18,       0) /* ArmorModVsAcid */
     , (2155768933,  19,       0) /* ArmorModVsElectric */
     , (2155768933, 159,       1) /* AbsorbMagicDamage */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2155768933,   1, 'Sanguinary Aegis') /* Name */
     , (2155768933,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2155768933,  25, 'P S Y C H O') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2155768933,   1,   33555834) /* Setup */
     , (2155768933,   8,       6360) /* Icon */
     , (2155768933, 8003,         16) /* PCAPRecordedObjectDesc - Attackable */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2155768933,   2, 2155768928) /* Container */;
