INSERT INTO `biota` (`id`, `weenie_Class_Id`, `weenie_Type`, `populated_Collection_Flags`)
VALUES (2693917646, 23356, 2, 2150720) /* Clothing */;

INSERT INTO `biota_properties_int` (`object_Id`, `type`, `value`)
VALUES (2693917646,   1,          2) /* ItemType - Armor */
     , (2693917646,   5,        600) /* EncumbranceVal */
     , (2693917646,   9,    2097152) /* ValidLocations - Shield */
     , (2693917646,  10,          0) /* CurrentWieldedLocation - None */
     , (2693917646,  19,          0) /* Value */
     , (2693917646,  28,          0) /* ArmorLevel */
     , (2693917646,  33,          1) /* Bonded - Bonded */
     , (2693917646,  36,       9999) /* ResistMagic */
     , (2693917646,  51,          4) /* CombatUse - Shield */
     , (2693917646, 107,          0) /* ItemCurMana */
     , (2693917646, 108,          0) /* ItemMaxMana */
     , (2693917646, 114,          0) /* Attuned - Normal */
     , (2693917646, 151,          2) /* HookType - Wall */
     , (2693917646, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `biota_properties_bool` (`object_Id`, `type`, `value`)
VALUES (2693917646,  69, False) /* IsSellable */
     , (2693917646,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `biota_properties_float` (`object_Id`, `type`, `value`)
VALUES (2693917646,  13,       0) /* ArmorModVsSlash */
     , (2693917646,  14,       0) /* ArmorModVsPierce */
     , (2693917646,  15,       0) /* ArmorModVsBludgeon */
     , (2693917646,  16,       0) /* ArmorModVsCold */
     , (2693917646,  17,       0) /* ArmorModVsFire */
     , (2693917646,  18,       0) /* ArmorModVsAcid */
     , (2693917646,  19,       0) /* ArmorModVsElectric */
     , (2693917646, 159,       1) /* AbsorbMagicDamage */;

INSERT INTO `biota_properties_string` (`object_Id`, `type`, `value`)
VALUES (2693917646,   1, 'Sanguinary Aegis') /* Name */
     , (2693917646,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (2693917646,  25, 'Spez') /* CraftsmanName */;

INSERT INTO `biota_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (2693917646,   1,   33555831) /* Setup */
     , (2693917646,   8,       6357) /* Icon */
     , (2693917646, 8003,         16) /* PCAPRecordedObjectDesc - Attackable */;

INSERT INTO `biota_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (2693917646,   2, 1343161453) /* Container */
     , (2693917646,   3,          0) /* Wielder */;
